### ISSUE TITLE
Release w/o polimec-node binaries?

### ISSUE THREAD

**Issue by Nexus2k** [Polimec/polimec-node#329]
Can you please make sure to actually supply the built binaries for each releases and ideally also provide a docker image?

**Comment by lrazovic** [comment]
Hi @Nexus2k, not all updates involve nodes; quite often, we only update the runtime. This is why [not every release](https://github.com/Polimec/polimec-node/releases) here on GitHub includes a new binary. Do you think we should clarify this better in our changelog?

**Comment by Nexus2k** [comment]
It's ok I guess, but docker images would be nice

**Comment by lrazovic** [comment]
Thank you for the feedback! You can find the images at this Docker Hub link: https://hub.docker.com/r/polimecfoundation/polimec/tags. I'll add this link to the README
