### ISSUE TITLE
When Docker image for v0.8.0?

### ISSUE THREAD

**Issue by Nexus2k** [Polimec/polimec-node#397]
I'm missing the docker image for v0.8.0, can you please build it and tag it with latest?

**Comment by lrazovic** [comment]
We encountered a minor issue with our CI, which prevented the automatic release. I’ve manually initiated the release process, and the latest version is now available on Docker Hub,[ tagged as latest and v0.8.0](https://hub.docker.com/repository/docker/polimecfoundation/polimec/tags).
